FROM node:20.19.6-alpine
WORKDIR /app
ENV PATH=/app/node_modules/.bin:$PATH
COPY package.json package-lock.json ./
COPY ./src ./src
COPY index.html ./
COPY vite.config.js ./
RUN npm install

EXPOSE 3000 
CMD ["npm", "run", "dev"]
