FROM python:3.13.3-slim
WORKDIR /app
COPY backend/requirements.txt backend/api.py ./
RUN pip install -r requirements.txt
ENV FLASK_ENV=development
ENV FLASK_APP=api.py

EXPOSE 8000
CMD ["flask", "run", "--host=0.0.0.0", "--port=8000"]